<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" import="java.util.HashMap, java.util.Map" %>

<%
    HashMap<String, String> faq = new HashMap<String, String>();
    faq.put("What is the global olive oil production?", 
        "Global olive oil production varies year to year depending on factors such as climate, cultivation practices, and olive harvests in different countries. On average, approximately 3 million tonnes of olive oil are produced globally each year. The major olive oil producers include Spain, Italy, Greece, and Turkey, which together account for a significant portion of the global output. Olive oil production is highly seasonal, and the quantities can fluctuate based on harvest conditions, including droughts or heavy rainfall in key producing regions.");
    faq.put("How much olive oil do 1000 kg of olives produce?", 
        "The yield of olive oil from 1000 kg of olives can range from 200 to 250 liters, depending on several factors such as the variety of olives, the ripeness of the fruit, the method of extraction, and the region of cultivation. Typically, olive oil is extracted by cold-pressing or using modern centrifugation methods that separate the oil from the olive paste. Some olive varieties, such as Arbequina or Koroneiki, tend to yield more oil than others. In regions with ideal growing conditions, the yield can be on the higher end of the spectrum.");
    faq.put("What are the best season, weather, and time conditions for olive harvesting?", 
        "The best conditions for olive harvesting are in the fall, typically from October to December, depending on the geographical location and variety of olives. Mild temperatures, with daytime highs between 15-20°C (59-68°F), are ideal for olive harvest, as they help preserve the quality of the oil and prevent the fruit from becoming overripe. Minimal rainfall is preferred as it helps maintain the health of the olive trees and avoids water-induced diseases. Harvesting too early or too late in the season can affect the oil’s flavor and aroma, with overripe olives yielding more oil but lower-quality oil.");
    faq.put("What is the difference between extra virgin olive oil and regular olive oil?", 
        "Extra virgin olive oil (EVOO) is the highest quality olive oil available and is made from the first cold-pressing of fresh olives without the use of heat or chemicals. EVOO retains the most nutrients and antioxidants, contributing to its rich, fruity, and peppery taste. It must have an acidity level of less than 0.8%. Regular olive oil, on the other hand, is often a blend of refined olive oil (which undergoes processing to remove impurities) and virgin olive oil (which is extracted in the same way as EVOO but may have a higher level of acidity). Regular olive oil has a more neutral flavor and a higher smoke point than extra virgin olive oil, making it suitable for cooking at higher temperatures.");
    faq.put("How long can olive oil be stored, and how should it be stored?", 
        "Olive oil can be stored for up to 18-24 months from its harvest date, though its quality gradually declines over time. To ensure longevity and preserve flavor, olive oil should be stored in a cool, dark place, away from light and heat. Exposure to oxygen, light, and heat can degrade the oil’s beneficial compounds and cause it to become rancid more quickly. It is best to keep olive oil in a sealed container, preferably in dark glass or tin, which helps shield it from UV rays. Additionally, storing it at room temperature, ideally between 15-18°C (59-64°F), prevents it from solidifying or oxidizing.");
    faq.put("What health benefits does olive oil provide?", 
        "Olive oil, particularly extra virgin olive oil, is known for its numerous health benefits, primarily due to its high content of monounsaturated fats and antioxidants. These healthy fats help reduce inflammation and support heart health by improving cholesterol levels and lowering the risk of cardiovascular disease. Olive oil is also rich in polyphenols, such as oleocanthal, which have been shown to have anti-inflammatory and anti-cancer properties. The oil’s antioxidant content can help combat oxidative stress, reducing the risk of chronic diseases like diabetes and Alzheimer’s. Additionally, its rich vitamin E content benefits skin health, supporting cell regeneration and acting as a natural moisturizer.");
    faq.put("Can olive oil be used for cooking, or is it best for dressings?", 
        "Olive oil is highly versatile and can be used for cooking at medium heat, making it suitable for a wide range of culinary applications. Extra virgin olive oil is particularly excellent for drizzling over salads, vegetables, and dips, or as a finishing oil for dishes due to its robust flavor and health benefits. However, regular olive oil or light olive oil, which has a higher smoke point, is a better choice for high-heat cooking methods such as sautéing, frying, and grilling. While EVOO may lose some of its delicate flavors when exposed to high temperatures, it still retains many of its health-promoting properties, making it suitable for various types of cooking.");
    faq.put("How do I recognize quality olive oil?", 
        "To recognize high-quality olive oil, look for bottles labeled as 'extra virgin,' 'cold-pressed,' and preferably with a harvest date, which ensures freshness. High-quality olive oil should have a rich, fruity flavor with peppery or grassy notes, and it should be free from rancid or metallic tastes. The oil should also have a balanced bitterness, which is indicative of a high antioxidant content. Avoid olive oils that are stored in clear plastic bottles or exposed to excessive light. In addition, reputable brands often provide information about the origin of the olives, production methods, and certifications, such as PDO (Protected Designation of Origin) or PGI (Protected Geographical Indication), which ensure the oil meets specific quality standards.");
    faq.put("Is olive oil good for skincare?", 
        "Yes, olive oil is widely used in skincare due to its moisturizing, anti-aging, and nourishing properties. It is rich in essential fatty acids, vitamin E, and antioxidants, which help protect the skin from free radical damage and promote healing. Olive oil can hydrate the skin, reduce the appearance of fine lines, and soothe dry or irritated skin. Its anti-inflammatory properties make it beneficial for conditions like eczema or psoriasis. Additionally, olive oil can be used as a natural makeup remover or a gentle exfoliator when mixed with sugar or salt. However, it’s important to test it on a small patch of skin first to ensure no allergic reaction occurs.");
    faq.put("How is olive oil made from olives?", 
        "Olive oil is made by first harvesting ripe olives, which are then washed and crushed into a paste. In traditional methods, the paste is pressed using a hydraulic press to extract the oil. Modern olive oil production uses centrifugal force or a continuous extraction system that separates the oil from the paste. The first pressing is referred to as the 'cold press,' which ensures the oil retains its maximum flavor and nutritional value. The extracted oil is then separated from any remaining water and solids, resulting in pure olive oil. If the oil is to be classified as extra virgin, it must meet stringent quality standards, including having low acidity and a rich, fresh taste.");
    faq.put("What is the ideal temperature for storing olive oil?", 
        "Olive oil should be stored at a stable room temperature, ideally between 15-18°C (59-64°F), away from heat sources and direct sunlight. Extreme temperatures, either too hot or too cold, can alter the oil chemical composition and flavor. Storing olive oil in a cool, dark place, such as a pantry or cupboard, ensures its quality is maintained for as long as possible. Some people recommend storing olive oil in the fridge, but this can cause the oil to solidify and become cloudy, which does not affect the quality of the oil but may alter its appearance temporarily.");
    faq.put("What is the shelf life of olive oil after opening?", 
        "After opening, olive oil typically lasts 6-12 months, depending on its quality and storage conditions. Over time, the oil will begin to lose its freshness, and its flavors may become rancid. To extend the shelf life, keep the oil tightly sealed in a dark bottle and store it away from heat and light. The key to determining if olive oil has gone bad is its smell and taste; rancid oil will have a sour or musty odor and a stale flavor. To preserve its quality, it’s best to consume olive oil within six months of opening for optimal freshness.");
    faq.put("Why do some olive oils have a bitter taste?", 
        "The bitter taste in olive oil is a result of the high concentration of polyphenols and antioxidants, specifically oleuropein and oleocanthal. These compounds, which are found in the olive's skin, leaves, and fruit, have beneficial health effects, including anti-inflammatory and antioxidant properties. The bitterness is actually a sign of fresh, high-quality olive oil, as older or improperly stored oils lose these compounds. While some people may not enjoy the bitter taste initially, it is considered a desirable trait in premium olive oils, especially in Mediterranean cuisine, where it adds depth and complexity to dishes.");
    faq.put("Can olive oil be used for frying?", 
        "Yes, olive oil can be used for frying, particularly for shallow frying or sautéing. Its smoke point varies depending on the type, with extra virgin olive oil having a smoke point around 190-220°C (374-428°F), while regular olive oil can withstand temperatures up to 230°C (446°F). While olive oil has a lower smoke point than some other oils, such as sunflower or canola oil, it is still suitable for most cooking methods. Additionally, olive oil retains many of its health benefits even when heated, as its high monounsaturated fat content is stable at moderate temperatures. However, it's best to avoid deep-frying with olive oil due to the high temperatures involved.");

    String userQuery = request.getParameter("query").toLowerCase().trim();
    String queryResponse = "Sorry, I couldn't find an answer to your question.";
    for (Map.Entry<String, String> entry : faq.entrySet()) {
        if (userQuery.contains(entry.getKey().toLowerCase())) {
            queryResponse = entry.getValue();
            break;
        }
    }
session.setAttribute("queryResponse", queryResponse);
response.sendRedirect("query_response.jsp");

%>
